apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-account-deployment
  labels:
    app: bank-account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-account
  template:
    metadata:
      labels:
        app: bank-account
    spec:
      initContainers:
        - name: wait-for-eureka
          image: busybox
          command: ['sh', '-c', 'until nc -z naming-server-service 8761; do echo waiting for eureka...; sleep 5; done']
      containers:
      - name: bank-account
        image: exchange-app/bank-account
        ports:
        - containerPort: 8200
        envFrom:
        - configMapRef:
            name: eureka-cm
---
apiVersion: v1
kind: Service
metadata:
  name: bank-account-service
spec:
  selector:
    app: bank-account
  ports:
  - protocol: TCP
    port: 8200
    targetPort: 8200