apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-exchange-deployment
  labels:
    app: crypto-exchange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-exchange
  template:
    metadata:
      labels:
        app: crypto-exchange
    spec:
      initContainers:
        - name: wait-for-eureka
          image: busybox
          command: ['sh', '-c', 'until nc -z naming-server-service 8761; do echo waiting for eureka...; sleep 5; done']
      containers:
      - name: crypto-exchange
        image: exchange-app/crypto-exchange
        ports:
        - containerPort: 8400
        envFrom:
        - configMapRef:
            name: eureka-cm
---
apiVersion: v1
kind: Service
metadata:
  name: crypto-exchange-service
spec:
  selector:
    app: crypto-exchange
  ports:
  - protocol: TCP
    port: 8400
    targetPort: 8400
