apiVersion: apps/v1
kind: Deployment
metadata:
  name: naming-server-deployment
  labels:
    app: naming-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: naming-server
  template:
    metadata:
      labels:
        app: naming-server
    spec:
      containers:
      - name: naming-server
        image: exchange-app/naming-server 
        ports:
        - containerPort: 8761
        readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 10
            periodSeconds: 5
        envFrom:
        - configMapRef:
            name: eureka-cm
---
apiVersion: v1
kind: Service
metadata:
  name: naming-server-service
  labels:
    app: naming-server
spec:
  selector:
    app: naming-server
  ports:
  - protocol: TCP
    port: 8761
    targetPort: 8761
