apiVersion: apps/v1
kind: Deployment
metadata:
  name: naming-server-deployment
  labels:
    app: naming-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: naming-server
  template:
    metadata:
      labels:
        app: naming-server
    spec:
      containers:
      - name: naming-server
        image: exchange-app/naming-server
        ports:
        - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: naming-server-service
spec:
  selector:
    app: naming-server
  ports:
  - protocol: TCP
    port: 8761
    targetPort: 8761
