apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-service-deployment
  labels:
    app: trade-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trade-service
  template:
    metadata:
      labels:
        app: trade-service
    spec:
      initContainers:
        - name: wait-for-eureka
          image: busybox
          command: ['sh', '-c', 'until nc -z naming-server-service 8761; do echo waiting for eureka...; sleep 5; done']
      containers:
      - name: trade-service
        image: exchange-app/trade-service
        ports:
        - containerPort: 8600
        envFrom:
        - configMapRef:
            name: eureka-cm
---
apiVersion: v1
kind: Service
metadata:
  name: trade-service-service
spec:
  selector:
    app: trade-service
  ports:
  - protocol: TCP
    port: 8600
    targetPort: 8600
