apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service-deployment
  labels:
    app: users-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      initContainers:
        - name: wait-for-eureka
          image: busybox
          command: ['sh', '-c', 'until nc -z naming-server-service 8761; do echo waiting for eureka...; sleep 5; done']
      containers:
      - name: users-service
        image: exchange-app/users-service
        ports:
        - containerPort: 8770
        envFrom:
        - configMapRef:
            name: eureka-cm
---
apiVersion: v1
kind: Service
metadata:
  name: users-service-service
spec:
  selector:
    app: users-service
  ports:
  - protocol: TCP
    port: 8770
    targetPort: 8770
