http:
  port: "8081"
db: 
 URL: "jdbc:postgresql://localhost:5432/GalerijaSlika"
 Driver: "org.postgresql.Driver"
 user: postgres
 password: postgres
  
file:
  chineseDir: "C:/Users/centar/AnypointStudio/studio-workspace/galerija-slika/src/main/resources/chineseERP"
  internalDir: "C:/Users/centar/AnypointStudio/studio-workspace/galerija-slika/src/main/resources/internalERP"